DROP TABLE IF EXISTS CAR;
CREATE TABLE CAR(

    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    BEST_DISCOUNT DOUBLE NOT NULL,

    BRAND CHARACTER VARYING(255) NOT NULL,

    MODEL CHARACTER VARYING(255) NOT NULL,

    PRICE_PR_DAY DOUBLE NOT NULL

)